swagger: "2.0"
info:
  description: This is property database
  version: "1.0"
  title: Swagger Property
consumes:
  - application/json
produces:
  - application/json

basePath: /

# Paths supported by the server application
paths:
  /api/cities:
    get:
      responses:
        '200':
          description: Success
      summary: List all cities
      operationId: post_request_city
      tags:
        - Property database
tags:
  - name: Property database
    description: Property database operations
responses:
  ParseError:
    description: When a mask can't be parsed
  MaskError:
    description: When any error occurs on mask
